name: Toolchain
# Build the submitted crate with a native toolchain from Alire

on:
  pull_request:

env:
  CHECKS_REPO: .

jobs:

  build:
    name: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # For the devel branch we need a compiler available to build alr in
    # setup-alire. We will be able to get rid of this once composite actions
    # support conditional steps.

    - name: Set up GNAT toolchain (FSF)
      if: (matrix.os == 'ubuntu-latest') && (contains(github.base_ref, 'devel-'))
      uses: ada-actions/toolchain@ce2020
      with:
        distrib: fsf # faster install?

    - name: Set up GNAT toolchain (Community)
      if: (matrix.os != 'ubuntu-latest') && (contains(github.base_ref, 'devel-'))
      uses: ada-actions/toolchain@ce2020
      with:
        distrib: community

    # By default, this sets up the newest indexed native toolchain
    - name: Set up stable `alr`
      if: contains(github.base_ref, 'stable-')
      uses: alire-project/setup-alire@v1
      with:
        version: 1.2.1  # This can be removed once it becomes the default

    # By default, this sets up the newest indexed native toolchain
    - name: Set up devel `alr`
      if: contains(github.base_ref, 'devel-')
      uses: alire-project/setup-alire@v1
      with:
        branch: 'master'

    - name: Install tar from msys2 (Windows) # Git tar in Actions VM does not seem to work)
      if: matrix.os == 'windows-latest'
      run: C:\Users\runneradmin\.cache\alire\msys64\usr\bin\pacman --noconfirm -S tar

    # Test all crates found in the index, as we want to verify checks for all kinds of
    # crates still work when checks are modified.
    - name: Test crate
      run: ${{env.CHECKS_REPO}}/scripts/gh-build-crate.sh
      shell: bash
      env:
        ALL_CRATES: TRUE
